### ISSUE TITLE
Project setup (Phase 2)

### ISSUE THREAD

**Issue by BenNewman90** [FACN4/Week6_The-Good_Boyz#3]
### General:
- [ ] Get API working and get a list of top films
- [x] Setup config.env file

### Client:
**index.html:**
- [x] Set up HTML structure for the search bar

**DOM.js:**
- [x] create /movieSearch click event which makes an XHR request to the server
- [x] create /movieReview click event which makes an XHR request to the server
- [ ] create /topMovies XHR request on page load event, and then update the HTML with the results

### Database:
**build.js**
- [x] Set up basic file #4 

**build.sql**
- [x] Make the following tables: users, movies, reviews and user-movie-review #5 

**connection.js**
- [x] Set up basic file... not really sure how to do this #6 

- [x] Set up the queries folders
### Server:
- [x] Set up httpReq file to make an API request with dummy data
- [x] create /movieSearch handler with uses an httpRequest and gets the current review from the 
database.
- [ ] create /movieReview handler which updates the database with the review
- [ ] create /topMovies handler which finds the top 5 rated movies, makes an httpRequest for each, and returns the data to the Client.
